const demoSales=[{fecha:"2026-03-01",canal:"Mercado Libre",producto:"Kit papelería escolar",cliente:"Cliente A",cantidad:4,precio_unitario:180,costo_unitario:110},{fecha:"2026-03-01",canal:"Tienda física",producto:"Libreta profesional",cliente:"Cliente B",cantidad:8,precio_unitario:42,costo_unitario:25},{fecha:"2026-03-02",canal:"WhatsApp",producto:"Paquete de plumas",cliente:"Cliente C",cantidad:5,precio_unitario:65,costo_unitario:38},{fecha:"2026-03-03",canal:"Amazon",producto:"Kit papelería escolar",cliente:"Cliente D",cantidad:2,precio_unitario:195,costo_unitario:115},{fecha:"2026-03-03",canal:"Shopify",producto:"Agenda personalizada",cliente:"Cliente E",cantidad:3,precio_unitario:220,costo_unitario:135},{fecha:"2026-03-04",canal:"Tienda física",producto:"Paquete de hojas",cliente:"Cliente F",cantidad:10,precio_unitario:85,costo_unitario:55},{fecha:"2026-03-05",canal:"Mercado Libre",producto:"Agenda personalizada",cliente:"Cliente G",cantidad:2,precio_unitario:230,costo_unitario:140},{fecha:"2026-03-05",canal:"WhatsApp",producto:"Kit oficina",cliente:"Cliente H",cantidad:1,precio_unitario:450,costo_unitario:280},{fecha:"2026-03-06",canal:"Shopify",producto:"Kit oficina",cliente:"Cliente I",cantidad:2,precio_unitario:450,costo_unitario:280},{fecha:"2026-03-07",canal:"Amazon",producto:"Paquete de plumas",cliente:"Cliente J",cantidad:6,precio_unitario:70,costo_unitario:38}];
const STORAGE_KEY="aynaa_sales_data";
const formatMoney=value=>new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN"}).format(value||0);
function normalizeRow(row){return{fecha:String(row.fecha||"").trim(),canal:String(row.canal||"").trim(),producto:String(row.producto||"").trim(),cliente:String(row.cliente||"").trim(),cantidad:Number(row.cantidad||0),precio_unitario:Number(row.precio_unitario||0),costo_unitario:Number(row.costo_unitario||0)}}
function getSales(){const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return demoSales;try{const data=JSON.parse(raw).map(normalizeRow);return data.length?data:demoSales}catch(error){return demoSales}}
function saveSales(data){localStorage.setItem(STORAGE_KEY,JSON.stringify(data.map(normalizeRow)))}
function groupBySum(data,key,valueFn){return data.reduce((acc,item)=>{const group=item[key]||"Sin dato";acc[group]=(acc[group]||0)+valueFn(item);return acc},{})}
function getRevenue(item){return Number(item.cantidad)*Number(item.precio_unitario)}
function getCost(item){return Number(item.cantidad)*Number(item.costo_unitario)}
function getProfit(item){return getRevenue(item)-getCost(item)}
function renderChannelOptions(data){const select=document.getElementById("channelFilter");const current=select.value;const channels=[...new Set(data.map(item=>item.canal).filter(Boolean))].sort();select.innerHTML='<option value="todos">Todos</option>';channels.forEach(channel=>{const option=document.createElement("option");option.value=channel;option.textContent=channel;select.appendChild(option)});if(channels.includes(current))select.value=current}
function getFilteredSales(){const data=getSales();const channel=document.getElementById("channelFilter").value;const search=document.getElementById("searchInput").value.toLowerCase().trim();return data.filter(item=>{const matchesChannel=channel==="todos"||item.canal===channel;const matchesSearch=!search||item.producto.toLowerCase().includes(search)||item.cliente.toLowerCase().includes(search);return matchesChannel&&matchesSearch})}
function getTopKey(grouped){const entries=Object.entries(grouped);if(!entries.length)return"-";return entries.sort((a,b)=>b[1]-a[1])[0][0]}
function renderKPIs(data){const totalRevenue=data.reduce((sum,item)=>sum+getRevenue(item),0);const totalProfit=data.reduce((sum,item)=>sum+getProfit(item),0);const orders=data.length;const ticket=orders?totalRevenue/orders:0;const salesByChannel=groupBySum(data,"canal",getRevenue);const salesByProduct=groupBySum(data,"producto",getRevenue);document.getElementById("kpiVentas").textContent=formatMoney(totalRevenue);document.getElementById("kpiUtilidad").textContent=formatMoney(totalProfit);document.getElementById("kpiPedidos").textContent=orders;document.getElementById("kpiTicket").textContent=formatMoney(ticket);document.getElementById("kpiCanal").textContent=getTopKey(salesByChannel);document.getElementById("kpiProducto").textContent=getTopKey(salesByProduct)}
function renderBarChart(containerId,grouped,limit=6){const container=document.getElementById(containerId);const entries=Object.entries(grouped).sort((a,b)=>b[1]-a[1]).slice(0,limit);container.innerHTML="";if(!entries.length){container.innerHTML='<p class="note">No hay datos para mostrar.</p>';return}const maxValue=Math.max(...entries.map(entry=>entry[1]));entries.forEach(([label,value])=>{const row=document.createElement("div");row.className="bar-row";const labelEl=document.createElement("span");labelEl.className="bar-label";labelEl.textContent=label;const track=document.createElement("div");track.className="bar-track";const fill=document.createElement("div");fill.className="bar-fill";fill.style.width=`${Math.max(value/maxValue*100,4)}%`;const valueEl=document.createElement("span");valueEl.className="bar-value";valueEl.textContent=formatMoney(value);track.appendChild(fill);row.appendChild(labelEl);row.appendChild(track);row.appendChild(valueEl);container.appendChild(row)})}
function renderCharts(data){renderBarChart("chartCanales",groupBySum(data,"canal",getRevenue),6);renderBarChart("chartProductos",groupBySum(data,"producto",getRevenue),6)}
function renderTable(data){const tbody=document.getElementById("salesTable");tbody.innerHTML="";data.forEach(item=>{const tr=document.createElement("tr");tr.innerHTML=`<td>${item.fecha}</td><td>${item.canal}</td><td>${item.producto}</td><td>${item.cliente}</td><td>${item.cantidad}</td><td>${formatMoney(getRevenue(item))}</td><td>${formatMoney(getProfit(item))}</td>`;tbody.appendChild(tr)});if(!data.length){tbody.innerHTML='<tr><td colspan="7">No hay registros con los filtros seleccionados.</td></tr>'}}
function renderApp(){const allSales=getSales();renderChannelOptions(allSales);const filteredSales=getFilteredSales();renderKPIs(filteredSales);renderCharts(filteredSales);renderTable(filteredSales)}
function parseCSV(text){const lines=text.split(/\r?\n/).map(line=>line.trim()).filter(Boolean);if(lines.length<2)throw new Error("El archivo debe tener encabezados y al menos una fila de datos.");const separator=lines[0].includes(";")?";":",";const headers=lines[0].split(separator).map(header=>header.trim().toLowerCase());const required=["fecha","canal","producto","cliente","cantidad","precio_unitario","costo_unitario"];const missing=required.filter(field=>!headers.includes(field));if(missing.length)throw new Error(`Faltan columnas obligatorias: ${missing.join(", ")}`);return lines.slice(1).map(line=>{const values=line.split(separator).map(value=>value.trim());const row={};headers.forEach((header,index)=>{row[header]=values[index]||""});return normalizeRow(row)})}
function handleCSVUpload(event){const file=event.target.files[0];const message=document.getElementById("uploadMessage");if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=parseCSV(reader.result);saveSales(data);message.style.color="#0f8a5f";message.textContent=`Archivo cargado correctamente. Registros importados: ${data.length}.`;renderApp();location.hash="#dashboard"}catch(error){message.textContent=error.message;message.style.color="#b00020"}};reader.readAsText(file,"UTF-8")}
function restoreDemoData(){saveSales(demoSales);document.getElementById("uploadMessage").style.color="#0f8a5f";document.getElementById("uploadMessage").textContent="Datos demo restaurados correctamente.";renderApp()}
function downloadReport(){const data=getFilteredSales();const totalRevenue=data.reduce((sum,item)=>sum+getRevenue(item),0);const totalProfit=data.reduce((sum,item)=>sum+getProfit(item),0);const lines=["REPORTE AYNAA - PORTAL DE ANALÍTICA",`Fecha de generación: ${new Date().toLocaleString("es-MX")}`,"",`Ventas totales: ${formatMoney(totalRevenue)}`,`Utilidad estimada: ${formatMoney(totalProfit)}`,`Pedidos: ${data.length}`,"","DETALLE","fecha,canal,producto,cliente,cantidad,ingreso,utilidad",...data.map(item=>[item.fecha,item.canal,item.producto,item.cliente,item.cantidad,getRevenue(item).toFixed(2),getProfit(item).toFixed(2)].join(","))];const blob=new Blob([lines.join("\n")],{type:"text/plain;charset=utf-8"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download="reporte_aynaa.txt";document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url)}
document.addEventListener("DOMContentLoaded",()=>{if(!localStorage.getItem(STORAGE_KEY))saveSales(demoSales);document.getElementById("channelFilter").addEventListener("change",renderApp);document.getElementById("searchInput").addEventListener("input",renderApp);document.getElementById("csvFile").addEventListener("change",handleCSVUpload);document.getElementById("loadDemo").addEventListener("click",restoreDemoData);document.getElementById("downloadReport").addEventListener("click",downloadReport);renderApp()});
